#!/bin/bash
#source: https://www.git-tower.com/learn/git/faq/change-author-name-email/

git filter-branch --env-filter '
WRONG_EMAIL="benjamin.j.schofield@gmail.com"
NEW_NAME="Benjscho"
NEW_EMAIL="benjamin.j.schofield+coding@gmail.com"

if [ "$GIT_COMMITTER_EMAIL" = "$WRONG_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$NEW_NAME"
    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$WRONG_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$NEW_NAME"
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
